# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x05login\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x18\n\nLoginReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x45\n\x0cLoginService\x12\x35\n\tLoginUser\x12\x13.login.LoginRequest\x1a\x11.login.LoginReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=22
  _LOGINREQUEST._serialized_end=72
  _LOGINREPLY._serialized_start=74
  _LOGINREPLY._serialized_end=98
  _LOGINSERVICE._serialized_start=100
  _LOGINSERVICE._serialized_end=169
# @@protoc_insertion_point(module_scope)
